#!/bin/bash

set -ex

repo=sm64-port

if [ ! -d $repo ]; then
  git clone https://github.com/Zoltar007/target_osx.git $repo
fi

# clear any changes in working directory
pushd $repo
git checkout -- .
popd

vert=quad.vert
frag=quad.frag
shaders=flexfov_shaders.c

# brew install glslang
glslangValidator $vert
glslangValidator $frag

echo "// AUTOGENERATED from $vert and $frag" > $shaders
echo "static const char *vs_src = " >> $shaders
awk '{ print "\"" $0 "\\n\"" }' $vert >> $shaders
echo ";" >> $shaders

echo "static const char *fs_src = " >> $shaders
awk '{ print "\"" $0 "\\n\"" }' $frag >> $shaders
echo ";" >> $shaders

cp flexfov.c flexfov.h $shaders $repo/src/game

rm $shaders

awk -v root="$repo" -f patch.awk patch.diff | ed


