#!/bin/bash

set -ex

vert=quad.vert
frag=quad.frag
outfile=src/game/flexfov_shaders.c

# brew install glslang
glslangValidator $vert
glslangValidator $frag

echo "// AUTOGENERATED by quad.sh (from $vert and $frag)" > $outfile
echo "static const char *vs_src = " >> $outfile
awk '{ print "\"" $0 "\\n\"" }' $vert >> $outfile
echo ";" >> $outfile

echo "static const char *fs_src = " >> $outfile
awk '{ print "\"" $0 "\\n\"" }' $frag >> $outfile
echo ";" >> $outfile
