#!/bin/bash

set -ex

# generate shader file
vert=quad.vert
frag=quad.frag

# brew install glslang
glslangValidator $vert
glslangValidator $frag

echo "// AUTOGENERATED from $vert and $frag"
echo "static const char *vs_src = "
awk '{ print "\"" $0 "\\n\"" }' $vert
echo ";"
echo "static const char *fs_src = "
awk '{ print "\"" $0 "\\n\"" }' $frag
echo ";"
